*&---------------------------------------------------------------------*
*&  Include           /SDOCS/SSPAY_INCL_DATA_DCRNLS
*&---------------------------------------------------------------------*

TYPES: BEGIN OF LS_INV_HDATA,
         REF_ID(255)                TYPE C,
         SSP_INVOICE_NO(255)        TYPE C,
         INV_NO(255)                TYPE C,
         COMPANY_CODE(255)          TYPE C,
         INVOICE_TYPE(255)          TYPE C,
         FREIGHT_VENDOR(255)        TYPE C,
         SYS_ID(255)                TYPE C,
         FSCL_YR(255)               TYPE C,
         VENDOR_INV_REFNO(255)      TYPE C,
         SPPLY_DATE(255)            TYPE C,
         DUE_DATE(255)              TYPE C,
         SUPPLIER_ID(255)           TYPE C,
         PO_NUMBER(255)             TYPE C,
         STATUS(255)                TYPE C,
         AMOUNT(255)                TYPE C,
         CURRENCY(255)              TYPE C,
         TAX_AMOUNT(255)            TYPE C,
         PAY_TERMS(255)             TYPE C,
         REMIT_ADDRESS(255)         TYPE C,
         SHIPTO_ADDRESS(255)        TYPE C,
         CREATED_DATE(255)          TYPE C,
         CREATED_TIME(255)          TYPE C,
         CR_TIME(255)               TYPE C,
         CREATOR(255)               TYPE C,
         INV_DATE(255)              TYPE C,
         FREIGHT_AMOUNT(255)        TYPE C,
         REQUESTOR_EMAIL(255)       TYPE C,
         NOTES(10000)               TYPE C,
         SUB_TOTAL(255)             TYPE C,
         TOTAL_DISCOUNT(255)        TYPE C,
         ADDITIONAL_DISCOUNT(255)   TYPE C,
         TAX_PERCENT(255)           TYPE C,
         FREIGHT_CARRIER(255)       TYPE C,
         INVOICE_CATEGORY(255)      TYPE C,
         CREDIT_MEMO(255)           TYPE C,
         EMPLOYEE_ID(255)           TYPE C,
         TITLE(255)                 TYPE C,
         SHOPPING_CART_NO(255)      TYPE C,
         CONFIDENTIAL(20)           TYPE C,
         EVENT_NUMBER(255)          TYPE C,
         EVENT_DESCRIPTION(255)     TYPE C,
         BANK_ACC_NO(255)           TYPE C,
         REQUESTOREMAIL(255)        TYPE C,
         BANKACCOUNTNUMBER(255)     TYPE C,
         ABANO(255)                 TYPE C,
         CHANNEL(255)               TYPE C,
         REQUESTER(255)             TYPE C,
         DATES_OF_SERVICE(255)      TYPE C,
         ISCREATED_BY_VENDOR(5)     TYPE C,
         INVOICE_TYPE_CATEGORY(255) TYPE C,
         SHIPMENT_TYPE(255)         TYPE C,
         PO_DESC(255)               TYPE C,
         CADS(255)                  TYPE C,
         AFTER_THEFACTPO(255)       TYPE C,
         TOTAL_INV_AMOUNT(255)      TYPE C,
         DOC_HEADER_TEXT(255)       TYPE C,
         YEAR(255)                  TYPE C,
         FI_INVOICE_YEAR(255)       TYPE C,
         SAP_INVOICE_NO(255)        TYPE C,
         POSTED_DATE(255)           TYPE C,
         PAYMENT_METHOD(255)        TYPE C,
         MARK_AS_ASSET(20)          TYPE C,
         SOURCE(255)                TYPE C,
         PRIORITY(255)              TYPE C,
         COMP_GST_NUMBER(255)       TYPE C,
         COMP_PAN_NUMBER(255)       TYPE C,
         EXPENSE_TYPE(255)          TYPE C,
         SPECIAL_GL(255)            TYPE C,
         ROUND_OFF(255)             TYPE C,
         HOUSE_BANK(255)            TYPE C,
         PAYMENT_BLOCK(255)         TYPE C,
         PAYMENT_REF(255)           TYPE C,
         ASSIGNMENT(255)            TYPE C,
         MSME(10)                   TYPE C,
         FREIGHT_CMT(255)           TYPE C,
         PERSON_RESPONSIBLE(255)    TYPE C,
         EXPENSE_CATEGORY(255)      TYPE C,
         DPR_INVYEAR(255)           TYPE C,
         DPR_INVNO(255)             TYPE C,
         ERP_DOCTYPE(255)           TYPE C,
         RESUBMITTED(255)           TYPE C,
         PARKED_USER(255)           TYPE C,
         PARKED_DATE(255)           TYPE C,
         LAST_ASSIGNED_DATE(255)    TYPE C,
         POSTING_DATE(255)          TYPE C,
         STAGE(255)                 TYPE C,
         STAGE_TYPE(255)            TYPE C,
         EXCEPTION(255)             TYPE C,
         WORKFLOW_TYPE(255)         TYPE C,
         BUSINESS_PLACE(255)        TYPE C,
         BUSINESS_AREA(255)         TYPE C,
         BUSINESS_SECTION(255)      TYPE C,
         RECEIVED_DATE(255)         TYPE C,
         OTHER_AMT(255)             TYPE C,
         OTHER_AMT_CMT(255)         TYPE C,
         PLNT(255)                  TYPE C,
       END OF LS_INV_HDATA.

TYPES:BEGIN OF LS_INV_LDATA,
        REF_ID(255)                TYPE C,
        INV_NO(255)                TYPE C,
        TYPE(255)                  TYPE C,
        PO(255)                    TYPE C,
        PO_LNE(255)                TYPE C,
        MAT_CODE(255)              TYPE C,
        MAT_DES(10000)             TYPE C,
        QTY(255)                   TYPE C,
        UOM(255)                   TYPE C,
        UNT_PRCE(255)              TYPE C,
        DLVRY_DATE(255)            TYPE C,
        SUPPLIER_PART_NO(255)      TYPE C,
        PLANT(255)                 TYPE C,
        SLOCATION(255)             TYPE C,
        GL_ACC_NO(255)             TYPE C,
        COST_CENTER(255)           TYPE C,
        WBS_ELEMENT_NO(255)        TYPE C,
        EXPENSE_TYPE(255)          TYPE C,
        DATE(15)                   TYPE C,
        THROUGHDATE(15)            TYPE C,
        MILEAGERATE(25)            TYPE C,
        MILES(255)                 TYPE C,
        ZIPCODE(255)               TYPE C,
        AMOUNT(25)                 TYPE C,
        DEPART_DATE(15)            TYPE C,
        DEPART_TIME(15)            TYPE C,
        RETURN_DATE(15)            TYPE C,
        RETURN_TIME(15)            TYPE C,
        DESC                       TYPE STRING,
        CURRENCY(25)               TYPE C,
        DATES_OF_SERVICE(255)      TYPE C,
        DIS_AMT(15)                TYPE C,
        CITY(255)                  TYPE C,
        COUNTY(255)                TYPE C,
        STATE(255)                 TYPE C,
        HOTEL_RATE(20)             TYPE C,
        MEALS_RATE(20)             TYPE C,
        GL_ACC_DESC(255)           TYPE C,
        COST_CENTER_DESC(255)      TYPE C,
        WBS_ELEMENT_DESC(255)      TYPE C,
        NET_AMT(25)                TYPE C,
        FUND_NO(255)               TYPE C,
        INV_UNT_PRCE(255)          TYPE C,
        PER(255)                   TYPE C,
        ASSET_CODE(255)            TYPE C,
        COMPANY_CODE(255)          TYPE C,
        ORDER_NUMBER(255)          TYPE C,
        ITEM_TEXT(10000)           TYPE C,
        MATCHED(25)                TYPE C,
        GRSES_NO(255)              TYPE C,
        GRSES_LNE(255)             TYPE C,
        DEBIT_CREDIT_INDICATOR(20) TYPE C,
        HSN_CODE(255)              TYPE C,
        BASE_UOM(255)              TYPE C,
        BUSINESS_PLACE(255)        TYPE C,
        TAXCODE(255)               TYPE C,
        DELV_NOTE(255)             TYPE C,
        TAX_AMT(255)               TYPE C,
        FREIGHT_AMOUNT(225)        TYPE C,
        TAX_PERCENT(225)           TYPE C,
        PO_DESC(225)               TYPE C,
        INV_VNDR_SELRSN(225)       TYPE C,
        INV_VNDR_AMT(225)          TYPE C,
        INV_VNDR_QTY(225)          TYPE C,
        PROFIT_CENTER(255)         TYPE C,
        INTERNAL_ORDER(255)        TYPE C,
        INTERNAL_ORDER_DESC(255)   TYPE C,
      END OF LS_INV_LDATA.

TYPES: BEGIN OF LS_ACNTASSIGTS,
         REF_ID(255)           TYPE C,
         LINE_NO(255)          TYPE C,
         PO_LNE(255)           TYPE C,
         PO(255)               TYPE C,
         MAT_CODE(255)         TYPE C,
         AMT(255)              TYPE C,
         GL_ACC_NO(255)        TYPE C,
         GL_ACC_DESC(255)      TYPE C,
         COST_CENTER(255)      TYPE C,
         COST_CENTER_DESC(255) TYPE C,
         TAXCODE(255)          TYPE C,
         TAXCODE_DESC(255)     TYPE C,
       END OF LS_ACNTASSIGTS.

TYPES: BEGIN OF LS_ATT,
         REF_ID(50)          TYPE C,
         INV_NO(12)          TYPE C,
         AR_ID(2)            TYPE C,
         AR_DOCID(40)        TYPE C,
         FL_NAME(255)        TYPE C,
         FL_TYPE(255)        TYPE C,
         ATTID(20)           TYPE C,
         DOC_TYPE(255)       TYPE C,
         DOC_EXPIRY_DATE(10) TYPE C,
         DOC_EXPIRY_TIME(10) TYPE C,
         CREATED_DATE(50)    TYPE C,
         CREATED_TIME(50)    TYPE C,
         CREATOR(255)        TYPE C,
         PRIMARY_DOC(255)    TYPE C,
       END OF LS_ATT.


TYPES: BEGIN OF LS_RMT,
         REF_ID(50)    TYPE C,
         NAME(255)     TYPE C,
         ADDRESS1(255) TYPE C,
         ADDRESS2(255) TYPE C,
         ADDRESS3(255) TYPE C,
         CITY(255)     TYPE C,
         STATE(255)    TYPE C,
         COUNTRY(255)  TYPE C,
         CNTRY(255)    TYPE C,
         ZIP(50)       TYPE C,
         LOCATION(255) TYPE C,
       END OF LS_RMT.

TYPES: BEGIN OF LS_SHP,
         REF_ID(50)    TYPE C,
         NAME(255)     TYPE C,
         ADDRESS1(255) TYPE C,
         ADDRESS2(255) TYPE C,
         ADDRESS3(255) TYPE C,
         CITY(255)     TYPE C,
         STATE(255)    TYPE C,
         COUNTRY(255)  TYPE C,
         ZIP(50)       TYPE C,
         LOCATION(255) TYPE C,
       END OF LS_SHP.

TYPES:BEGIN OF LS_WORKFLOW,
        REF_ID(50)              TYPE C,
        WORK_ITEM_ID(255)       TYPE C,
        CANEDIT(255)            TYPE C,
        STEP(10)                TYPE C,
        CAN_APPROVER_CHANGE(10) TYPE C,
        STAGE_NUMBER(255)       TYPE C,
        STAGE_TYPE(255)         TYPE C,
        STAGE_NAME(255)         TYPE C,
        STL(255)                TYPE C,
      END OF LS_WORKFLOW.

TYPES:BEGIN OF LS_WF_ACTIVITY,
        REF_ID(50) TYPE C,
        AGENT(255) TYPE C,
        USER(255)  TYPE C,
      END OF LS_WF_ACTIVITY.

TYPES:BEGIN OF LS_ACTIVITIES,
        REF_ID(50)       TYPE C,
        NAME(255)        TYPE C,
        CODE(255)        TYPE C,
        LABLE(255)       TYPE C,
        COMMENT_REQ(255) TYPE C,
        ENABLED(255)     TYPE C,
      END OF LS_ACTIVITIES.

TYPES:BEGIN OF LS_EXCEPTIONS,
        REF_ID(50) TYPE C,
        TYPE(255)  TYPE C,
        TEXT(255)  TYPE C,
      END OF LS_EXCEPTIONS.

TYPES:BEGIN OF LS_USERS,
        REF_ID(50)    TYPE C,
        APPROVER(255) TYPE c,
      END OF LS_USERS.

TYPES:BEGIN OF LS_RESULTS,
        STATUS(255)  TYPE C,
        MESSAGE(255) TYPE C,
      END OF LS_RESULTS.

TYPES: BEGIN OF LS_ASTAGES,
         STAGE_NAME(255)    TYPE C,
         STAGE_TYPE(255)    TYPE C,
         AGENT_ID(255)      TYPE C,
         CANEDIT(255)       TYPE C,
         STAGE_CLEARED(255) TYPE C,
         CONDITIONAL(255)   TYPE C,
       END OF  LS_ASTAGES.

DATA: BEGIN OF T_FILE_DOCTYPE OCCURS 0,
        ATT_DOCTYPE TYPE CHAR30,
      END OF T_FILE_DOCTYPE.

DATA:LV_EXP_TYPE_V TYPE CHAR50.
TYPES:BEGIN OF FS_DOC,
        CHANNEL TYPE /SDOCS/SSPY_HD-CHANNEL,
      END OF FS_DOC.

TYPES:BEGIN OF LS_BRULES,
        IS_PASSED(50)           TYPE C,
        IS_AGENT_PASSED(50)     TYPE C,
        EXCEPTION_CLEARED(50)   TYPE C,
        CLEAR_EXCEPTION(50)     TYPE C,
        CLEARABLE_EXCEPTION(50) TYPE C,
        DATA(50)                TYPE C,
        RULE_ID(50)             TYPE C,
        EXCEPTION(50)           TYPE C,
        INDEX(50)               TYPE C,
        AGENT_ID(50)            TYPE C,
        AGENT(255)              TYPE C,
        ENABLED(50)             TYPE C,
        ERROR_MESSAGE(255)      TYPE C,
*        DATA(255)               TYPE C,
        TITLE(255)              TYPE C,
        DESC(255)               TYPE C,
        DATA_OBJ(255)           TYPE C,
        TYPE(255)               TYPE C,
        PRE_DFN_FN(255)         TYPE C,
        CATEGORY(255)           TYPE C,
        STAGE_NAME(255)         TYPE C,
      END OF LS_BRULES.

TYPES: BEGIN OF LS_DATAS,
         RULE_ID(255) TYPE C,
         DATA(255)    TYPE C,
       END OF LS_DATAS.

TYPES:BEGIN OF LS_DRSLTS,
        SSP_INVOICE_NO(255)   TYPE C,
        INV_NO(255)           TYPE C,
        INVOICE_CATEGORY(255) TYPE C,
      END OF LS_DRSLTS.

TYPES:BEGIN OF LS_PORHD,
        REF_ID(255)          TYPE C,
        REQUEST_ID(255)      TYPE C,
        CCODE(255)           TYPE C,
        PORG(255)            TYPE C,
        PGRP(255)            TYPE C,
        CURRENCY(255)        TYPE C,
        S_ID(255)            TYPE C,
        CREATED_DATE(255)    TYPE C,
        CREATED_TIME(255)    TYPE C,
        CREATED_BY(255)      TYPE C,
        PLANT(255)           TYPE C,
        TOTAL_AMT(255)       TYPE C,
        IS_SAP_SYNC(255)     TYPE C,
        IS_SAP_SYNC_ACK(255) TYPE C,
        TYPE(255)            TYPE C,
        AGENT_NAME(255)      TYPE C,
        REQ_EMAIL(255)       TYPE C,
        PAYTERMS(255)        TYPE C,
        REQUESTOR_EMAIL(255) TYPE C,
        SUPPLIER_ID(255)     TYPE C,
        TOTAL_AMOUNT(255)    TYPE C,
        INITATOR(255)        TYPE C,
        RECEIVER_EMAIL(255)  TYPE C,
        REQUSET_ID(255)      TYPE C,
        PRR_REF_ID(255)      TYPE C,
      END OF LS_PORHD.
TYPES:BEGIN OF LS_PORLNS,
        ID(255)           TYPE C,
        REF_ID(255)       TYPE C,
        PO_LNE(255)       TYPE C,
        MAT_CODE(255)     TYPE C,
        MAT_DES(255)      TYPE C,
        PO_QTY(255)       TYPE C,
        POR_QTY(255)      TYPE C,
        PO_UOM(255)       TYPE C,
        PO_UNT_PRCE(255)  TYPE C,
        POR_UNT_PRCE(255) TYPE C,
        PLANT(255)        TYPE C,
        SLOCATION(255)    TYPE C,
        DLVRY_DATE(255)   TYPE C,
        DIS_AMT(255)      TYPE C,
        PER(255)          TYPE C,
        PER_UOM(255)      TYPE C,
        NET_VALUE(255)    TYPE C,
        GRN_REQUIRED(255) TYPE C,
        DELETED(255)      TYPE C,
        SUPPLIED_BY(255)  TYPE C,
        CURRENCY(255)     TYPE C,
        GL_ACC_NO(255)    TYPE C,
        TAX_AMT(255)      TYPE C,
        CATEGORY(255)     TYPE C,
        MAT_GROUP(255)    TYPE C,
        COST_CENTER(255)  TYPE C,
        FREIGHT_AMT(255)  TYPE C,
        GI_QTY(255)       TYPE C,
        GI_UOM(255)       TYPE C,
        GI_UNT_PRCE(255)  TYPE C,
        UNIT_PRICE(25)    TYPE C,
        ITEM_NO(25)       TYPE C,
      END OF  LS_PORLNS.

TYPES:BEGIN OF GS_SDATA,
        REF_ID(255)          TYPE C,
        REQUEST_ID(255)      TYPE C,
        CCODE(255)           TYPE C,
        PORG(255)            TYPE C,
        PGRP(255)            TYPE C,
        CURRENCY(255)        TYPE C,
        S_ID(255)            TYPE C,
        CREATED_DATE(255)    TYPE C,
        CREATED_TIME(255)    TYPE C,
        CREATED_BY(255)      TYPE C,
        PLANT(255)           TYPE C,
        TOTAL_AMT(255)       TYPE C,
        TOTAL_AMOUNT(255)    TYPE C,
        IS_SAP_SYNC(255)     TYPE C,
        IS_SAP_SYNC_ACK(255) TYPE C,
        TYPE(255)            TYPE C,
        AGENT_NAME(255)      TYPE C,
        REQ_EMAIL(255)       TYPE C,
        PAYTERMS(255)        TYPE C,
        REQUESTOR_EMAIL(255) TYPE C,
        SUPPLIER_ID(255)     TYPE C,
        INITATOR(255)        TYPE C,
      END OF GS_SDATA.

TYPES:BEGIN OF GS_LINEITEMS_POR,
        ID(255)                      TYPE C,
        REF_ID(255)                  TYPE C,
        PO_LNE(255)                  TYPE C,
        MAT_CODE(255)                TYPE C,
        MAT_DES(255)                 TYPE C,
        PO_QTY(255)                  TYPE C,
        PO_UOM(255)                  TYPE C,
        PO_UNT_PRCE(255)             TYPE C,
        PLANT(255)                   TYPE C,
        SLOCATION(255)               TYPE C,
        DLVRY_DATE(255)              TYPE C,
        DIS_AMT(255)                 TYPE C,
        PER(255)                     TYPE C,
        PER_UOM(255)                 TYPE C,
        NET_VALUE(255)               TYPE C,
        GRN_REQUIRED(255)            TYPE C,
        DELETED(255)                 TYPE C,
        SUPPLIED_BY(255)             TYPE C,
        CURRENCY(255)                TYPE C,
        GL_ACC_NO(255)               TYPE C,
        TAX_AMT(255)                 TYPE C,
        CATEGORY(255)                TYPE C,
        MAT_GROUP(255)               TYPE C,
        COST_CENTER(255)             TYPE C,
        ACCOUNT_ASSIGNMENT_TYPE(255) TYPE C,
      END OF GS_LINEITEMS_POR.

TYPES:BEGIN OF GS_LINEITEMS,
        ID(255)                      TYPE C,
        REF_ID(255)                  TYPE C,
        LINE_NO(255)                 TYPE C,
        MATERIAL_CODE(255)           TYPE C,
        MATERIAL_DESC(255)           TYPE C,
        MATERIAL_GRP(255)            TYPE C,
        IS_MATERIAL_MASTER(255)      TYPE C,
        AMT(255)                     TYPE C,
        UOM(255)                     TYPE C,
        QTY(255)                     TYPE C,
        UNIT_PRICE(255)              TYPE C,
        CURRENCY(255)                TYPE C,
        PLANT(255)                   TYPE C,
        DELIVERY_DATE(255)           TYPE C,
        ACCOUNT_ASSIGNMENT_TYPE(255) TYPE C,
        COST_CENTER(255)             TYPE C,
        SUPPLIED_BY(255)             TYPE C,
        CATEGORY(255)                TYPE C,
        GL_ACC_NO(255)               TYPE C,
        PER(255)                     TYPE C,
        SLOCATION(255)               TYPE C,
      END OF GS_LINEITEMS.


TYPES : BEGIN OF LS_BANK,
          REF_ID(50)       TYPE C,
          ACCNAME(255)     TYPE C,
          NAME(255)        TYPE C,
          ACC_NUMBER(255)  TYPE C,
          SWIFT_CODE(255)  TYPE C,
          ROUT_NUMBER(255) TYPE C,
          IBAN(255)        TYPE C,
        END OF LS_BANK.


TYPES:BEGIN OF GS_WF_ACTIVITY,
        REF_ID(50) TYPE C,
        AGENT(255) TYPE C,
        USER(255)  TYPE C,
      END OF GS_WF_ACTIVITY.

TYPES:BEGIN OF GS_USERS,
        REF_ID(50)    TYPE C,
        APPROVER(255) TYPE C,
      END OF GS_USERS.

TYPES:BEGIN OF GS_ACTIVITIES,
        REF_ID(50)     TYPE C,
        NAME(255)      TYPE C,
        CODE(255)      TYPE C,
        LABLE(255)     TYPE C,
        COMMENT_REQ(5) TYPE C,
        ENABLED(255)   TYPE C,
      END OF GS_ACTIVITIES.

TYPES:BEGIN OF GS_EXCEPTIONS,
        REF_ID(50)              TYPE C,
        IS_PASSED(50)           TYPE C,
        RULE_ID(50)             TYPE C,
        TITLE(50)               TYPE C,
        DESCRIPTION(50)         TYPE C,
        DATA_OBJ(50)            TYPE C,
        TYPE(50)                TYPE C,
        PRE_DFN_FN(50)          TYPE C,
        CLEAR_EXCEPTION(50)     TYPE C,
        CLEARABLE_EXCEPTION(50) TYPE C,
      END OF GS_EXCEPTIONS.

TYPES: BEGIN OF TY_STAGES,
         STAGE_NAME(255)         TYPE C,
         STAGE_NUMBER(255)       TYPE C,
         STAGE_TYPE(255)         TYPE C,
         NOTES(255)              TYPE C,
         AGENT_ID(255)           TYPE C,
         CANEDIT(255)            TYPE C,
         STAGE_CLEARED(255)      TYPE C,
         STL_TAB(255)            TYPE C,
         CONDITIONAL(255)        TYPE C,
         CONDITIONAL_OBJECT(255) TYPE C,
         CONDITIONAL_EXP(255)    TYPE C,
       END OF TY_STAGES.

TYPES: BEGIN OF TY_ACTVYS,
         CODE(255)             TYPE C,
         NAME(255)             TYPE C,
         UI_CLASS(255)         TYPE C,
         COMMENT_REQUIRED(255) TYPE C,
       END OF TY_ACTVYS.

TYPES: BEGIN OF TY_BSRULES,
         IS_PASSED(255)           TYPE C,
         RULE_ID(255)             TYPE C,
         TITLE(255)               TYPE C,
         DESCRIPTION(255)         TYPE C,
         DATA_OBJ(255)            TYPE C,
         TYPE(255)                TYPE C,
         PRE_DFN_FN(255)          TYPE C,
         ERROR_MESSAGE(255)       TYPE C,
         CLEAR_EXCEPTION(255)     TYPE C,
         CLEARABLE_EXCEPTION(255) TYPE C,
       END OF TY_BSRULES.

TYPES: BEGIN OF GS_DRSLTS,
         REF_ID(50)            TYPE C,
         SSP_INVOICE_NO(255)   TYPE C,
         INV_NO(255)           TYPE C,
         INVOICE_CATEGORY(255) TYPE C,
       END OF GS_DRSLTS.

TYPES: BEGIN OF GS_INVPOS,
         REF_ID(255)    TYPE C,
         PO_NUMBER(255) TYPE C,
       END OF  GS_INVPOS.


DATA:GT_SWORKFLOW   TYPE TABLE OF LS_WORKFLOW,
     GT_SWFACTY     TYPE TABLE OF GS_WF_ACTIVITY,
     GT_SUSERS      TYPE TABLE OF GS_USERS,
     GT_SACTIVITIES TYPE TABLE OF GS_ACTIVITIES,
     GT_BRULES      TYPE TABLE OF GS_EXCEPTIONS,
     GT_EXPNS       TYPE TABLE OF GS_EXCEPTIONS,
     GT_DRSLTS      TYPE TABLE OF GS_DRSLTS,
     GT_INVPOS      TYPE TABLE OF GS_INVPOS,
     GT_DATAS       TYPE TABLE OF LS_DATAS,
     SWA_EXPNS      TYPE GS_EXCEPTIONS,
     WA_SWORKFLOW   TYPE  LS_WORKFLOW,
     WA_SWFACTY     TYPE  GS_WF_ACTIVITY,
     SWA_USERS      TYPE  GS_USERS,
     SWA_ACTIVITIES TYPE  GS_ACTIVITIES,
     SWA_BRULES     TYPE  GS_EXCEPTIONS,
     SWA_DRSLTS     TYPE  GS_DRSLTS,
     SWA_DATAS      TYPE  LS_DATAS,
     WA_INVPOS      TYPE  GS_INVPOS.


DATA:GT_STAGES  TYPE TABLE OF TY_STAGES,
     GT_ACTVYS  TYPE TABLE OF TY_ACTVYS,
     GT_BSRULES TYPE TABLE OF TY_STAGES,
     WA_STAGES  TYPE  TY_STAGES,
     WA_ACTVYS  TYPE  TY_ACTVYS,
     WA_BSRULES TYPE  TY_BSRULES.


DATA:LT_WORKFLOW    TYPE TABLE OF LS_WORKFLOW,
     LT_WF_ACTIVITY TYPE TABLE OF LS_WF_ACTIVITY,
     LT_ACTIVITIES  TYPE TABLE OF LS_ACTIVITIES,
     LT_EXCEPTIONS  TYPE TABLE OF LS_EXCEPTIONS,
     LT_USERS       TYPE TABLE OF LS_USERS,
     LT_RESULTS     TYPE TABLE OF LS_RESULTS,
     LT_BANK        TYPE TABLE OF LS_BANK,
     LT_BRULES      TYPE TABLE OF LS_BRULES,
     LT_PORLN       TYPE TABLE OF LS_PORLNS,
     LT_PORHD       TYPE TABLE OF LS_PORHD,
     GT_T_POR       TYPE TABLE OF GS_LINEITEMS_POR,
     GT_T_LN        TYPE TABLE OF GS_LINEITEMS,
     GT_T_HD        TYPE TABLE OF GS_SDATA.

*     lT_DRSLTS      TYPE TABLE OF LS_DRSLTS.

DATA: LT_INV_HDATA   TYPE TABLE OF LS_INV_HDATA,
      LT_INV_LDATA   TYPE TABLE OF LS_INV_LDATA,
      LT_ATT         TYPE TABLE OF LS_ATT,
      LT_ATTACH_RCV  TYPE TABLE OF /SDOCS/SSPY_ATTA,
      LT_LN          TYPE TABLE OF /SDOCS/SSPY_LN,
      LT_RMT         TYPE TABLE OF LS_RMT,
      LT_SHP         TYPE TABLE OF LS_SHP,
      LT_LOG         TYPE TABLE OF /SDOCS/SSPY_LOG,
      LT_LOG1        TYPE TABLE OF /SDOCS/SSPY_LOG,
      LT_DOCTYPE     TYPE TABLE OF  /SDOCS/SSPY_DTYP,
      LT_SAPUERS     TYPE TABLE OF /SDOCS/S1_USR,
      LT_ACNTASSIGTS TYPE TABLE OF LS_ACNTASSIGTS,
      LT_ASTAGES     TYPE TABLE OF LS_ASTAGES,
      LT_HPO         TYPE TABLE OF /SDOCS/S1_HMULTI.



DATA: WA_INV_HDATA   TYPE LS_INV_HDATA,
      WA_INV_LDATA   TYPE LS_INV_LDATA,
      WA_SAPUERS     TYPE  /SDOCS/S1_USR,
      WA_ATT         TYPE LS_ATT,
      WA_ACTIVITIES  TYPE LS_ACTIVITIES,
      WA_WORKFLOW    TYPE LS_WORKFLOW,
      WA_WF_ACTIVITY TYPE LS_WF_ACTIVITY,
      WA_EXCEPTIONS  TYPE LS_EXCEPTIONS,
      WA_DOCTYPE     TYPE /SDOCS/SSPY_DTYP-DOCTYPE,
      WA_ATTACH      TYPE /SDOCS/SSPY_ATTA,
      WA_RMT         TYPE  LS_RMT,
      WA_SHP         TYPE  LS_SHP,
      WA_DOC1        TYPE FS_DOC,
      WA_PORLN       TYPE LS_PORLNS,
      WA_PORHD       TYPE LS_PORHD,
      WA_RESULTS     TYPE LS_RESULTS,
      WA_ACTIVITY    TYPE /SDOCS/SSPY_ACT_CODE,
      WA_INV         TYPE /SDOCS/SSPY_DTYP,
      WA_T_HD        TYPE GS_SDATA,
      WA_T_POR       TYPE GS_LINEITEMS_POR,
      WA_T_LN        TYPE GS_LINEITEMS,
      LV_NO_WF,
      LV_PO          TYPE EBELN,
      WA_USERS       TYPE LS_USERS,
      WA_BRULES      TYPE LS_BRULES,
      WA_BANK1       TYPE LS_BANK,
      WA_ASTAGES     TYPE LS_ASTAGES,
      WA_HPO         TYPE /SDOCS/S1_HMULTI,
      WA_ACNTASSIGTS TYPE LS_ACNTASSIGTS.
*      wa_drslts      TYPE ls_drslts.

DATA:WA_LOG_RCV   TYPE /SDOCS/SSPY_LOG,
     LV_SEQID     TYPE NUMC5,
     LOG_SEQ_ID   TYPE /SDOCS/SSPY_LOG-SEQ_ID,
     RE_WF_FLG,
     LV_SC_FAILED ,
     GV_LGL       TYPE TBDLS-LOGSYS.
DATA:LV_WRBTR      TYPE P DECIMALS 2,
     LV_ADDAMNT    TYPE P DECIMALS 2,
     LV_TAXAMNT    TYPE /SDOCS/SSPY_HD-TOT_AMT,
     GV_SUM1       TYPE DECFLOAT34,
     LT_FINAL_AMNT TYPE /SDOCS/SSPY_HD-TOT_AMT,
     L_LFA1_V2     TYPE LFA1-NAME1.

DATA:GV_REFID(255) TYPE C.

DATA:GV_ARDOCTYPE TYPE SAEOBJART.
DATA:LV_VORNA TYPE PA0002-VORNA,
     LV_NACHN TYPE PA0002-NACHN.
DATA:LV_ACTIVITY TYPE /SDOCS/SSPY_LOG-ACTVTY_ID.
DATA:L_PRPS TYPE PRPS.
DATA:L_PO_NO_SHC TYPE /SDOCS/SSPY_HD-EBELN.
DATA:WA_MSEG_GR TYPE MSEG.
DATA:LV_SUCCESS_GRN TYPE CHAR1.
DATA:LV_CNT_AT TYPE INT4.
DATA:GV_SYNC_FLAG.
DATA:BEGIN OF LT_PAYH OCCURS 0,
       DOCID TYPE /SDOCS/SSPY_HD-DOCID,
*       WF_USER TYPE /SDOCS/SSPY_HD-WF_USER,
     END OF LT_PAYH.
TYPES:BEGIN OF FS_PORTAL_ACT,
        ACT       TYPE /SDOCS/SSPY_ACT_CODE,
        ACT_TEXT  TYPE /SDOCS/SSPY_CHAR30,
        ACT_BTEXT TYPE /SDOCS/SSPY_CHAR30,
      END OF FS_PORTAL_ACT.
DATA:WA_PORTAL_ACT TYPE FS_PORTAL_ACT,
     IT_PORTAL_ACT TYPE TABLE OF FS_PORTAL_ACT.
DATA:LV_EMAIL TYPE  ADR6-SMTP_ADDR.

*data:gt_recent_act       type TABLE OF gs_recent_act,
*     gs_recent_act  like line of gt_recent_act.
DATA:BEGIN OF IT_DOCIDS OCCURS 0,
       DOCID TYPE /SDOCS/SSPY_DOCID,
     END OF  IT_DOCIDS.

DATA:BEGIN OF IT_EKPO OCCURS 0,
       EBELN TYPE EKKO-EBELN,
       EBELP TYPE EKPO-EBELN,
       WEPOS TYPE EKPO-WEPOS,
       WEBRE TYPE EKPO-WEBRE,
     END OF IT_EKPO.

TYPES:BEGIN OF TT_AR6,
        ADDRNUMBER TYPE ADR6-ADDRNUMBER,
        PERSNUMBER TYPE ADR6-PERSNUMBER,
        SMTP_ADDR  TYPE ADR6-SMTP_ADDR,
      END OF TT_AR6.

TYPES:BEGIN OF TT_USR21,
        BNAME      TYPE USR21-BNAME,
        PERSNUMBER TYPE USR21-PERSNUMBER,
        ADDRNUMBER TYPE USR21-ADDRNUMBER,
      END OF TT_USR21.

TYPES:BEGIN OF GS_SDATA_VRR,
        REF_ID(255)                 TYPE C,
        SUPPLR_NAME(255)            TYPE C,
        USER_REF_ID(255)            TYPE C,
        SSN_NO(255)                 TYPE C,
        REQUESTOR_EMAIL(255)        TYPE C,
        EMP_ID_NO(255)              TYPE C,
        PHONE_NUMBER(255)           TYPE C,
        PHONE_CNTRYCODE(255)        TYPE C,
        PHONE_EXT(255)              TYPE C,
        FAX_NUMBER(255)             TYPE C,
        FAX_CNTRYCODE(255)          TYPE C,
        COMP_CODE(255)              TYPE C,
        PRIMARY_EMAIL(255)          TYPE C,
        DBA_NAME(255)               TYPE C,
        LEGAL_NAME(255)             TYPE C,
        W9_FORM_SIGNATURE_DATE(255) TYPE C,
        NO_ALTERNATE_PAYMENT(255)   TYPE C,
        WORKFLOW_TYPE(255)          TYPE C,
        COMPANY_CODE(255)           TYPE C,
        PAYMENT_METHOD(255)         TYPE C,
        PAYMENT_TERMS(255)          TYPE C,
        RELEASE_GROUP(255)          TYPE C,
        PURCHASING_GROUP(255)       TYPE C,
        PURCHASING_ORG(255)         TYPE C,
        RECONCILIATION_ACCOUNT(255) TYPE C,
        CURRENCY(255)               TYPE C,
        WORKITEM_CREATED_DATE(255)  TYPE C,
        WORKITEM_CREATED_TIME(255)  TYPE C,
        SUBMIT_FOR_BID(255)         TYPE C,
        SUBMIT_FOR_BID_REASON(255)  TYPE C,
        STATUS(255)                 TYPE C,
      END OF GS_SDATA_VRR.

TYPES:BEGIN OF GS_KEYDATA,
        REF_ID(30)               TYPE C,
        TYPE(50)                 TYPE C,
        SUPPLIERID(20)           TYPE C,
        COMPANY_CODE(10)         TYPE C,
        USER_REF_ID(20)          TYPE C,
        ACTION(20)               TYPE C,
        NO_DBE_ANYMORE(20)       TYPE C,
        SET_AS_PRIMARY_EMAIL(20) TYPE C,
        REQUESTOR_EMAIL(255)     TYPE C,
        WORKFLOW_TYPE(255)       TYPE C,
      END OF GS_KEYDATA.

TYPES:BEGIN OF GS_VALUE,
        REF_ID(50)       TYPE C,
        FIELD_NAME(255)  TYPE C,
        FIELD_VALUE(255) TYPE C,
      END OF GS_VALUE.

TYPES:BEGIN OF GS_OTH,
        REF_ID       TYPE CHAR255,
        COMMENT_TEXT TYPE CHAR255,
      END OF GS_OTH.

DATA:GT_OTH TYPE  TABLE OF GS_OTH,
     WA_OTH TYPE GS_OTH.

DATA:WA_KEYDATA TYPE GS_KEYDATA,
     GT_KEYDATA TYPE TABLE OF GS_KEYDATA.

DATA:WA_VALUE1 TYPE GS_VALUE,
     GT_VALUE  TYPE TABLE OF GS_VALUE.

TYPES:BEGIN OF GS_ADDRESS,
        REF_ID(255) TYPE C,
        ADDRESS1    TYPE CHAR255,
        ADDRESS2    TYPE CHAR255,
        ADDRESS3    TYPE CHAR255,
        PHONE(255)  TYPE C,
        CITY        TYPE CHAR255,
        CNTRY       TYPE CHAR255,
        STATE       TYPE CHAR255,
        ZIP         TYPE CHAR255,
        LOCATION    TYPE CHAR255,
        COUNTY      TYPE CHAR255,
      END OF GS_ADDRESS.

TYPES:BEGIN OF GS_BNK_DTLS,
        REF_ID(255)         TYPE C,
        BNK_ACC_NO          TYPE CHAR255,
        BNK_NAME(255)       TYPE C,
        BNK_ADDRESS(255)    TYPE C,
        BNK_IFSC_CODE(255)  TYPE C,
        BNK_SWIFT_CODE(255) TYPE C,
      END OF GS_BNK_DTLS.
TYPES:BEGIN OF TY_STATUS,
        REF_ID(255) TYPE C,
        STATUS(255) TYPE C,
      END OF TY_STATUS.
TYPES: BEGIN OF GS_ATT,
         REF_ID(255)       TYPE C,
         AR_ID(255)        TYPE C,
         AR_DOCID(255)     TYPE C,
         FL_NAME(255)      TYPE C,
         FL_TYPE(255)      TYPE C,
         DOC_TYPE(255)     TYPE C,
         DOC_EXPIRY_DATE   TYPE CHAR255,
         DOC_EXPIRY_TIME   TYPE CHAR255,
         CREATED_DATE(255) TYPE C,
         CREATED_TIME(255) TYPE C,
         CREATOR(255)      TYPE C,
         ATTID             TYPE NUMC5,
       END OF GS_ATT.

TYPES:BEGIN OF GS_CNTCTS,
        REF_ID(255)        TYPE C,
        FRST_NAME          TYPE CHAR255,
        LST_NAME           TYPE CHAR255,
        EMAL               TYPE CHAR255,
        PHONE_NUMBER(255)  TYPE C,
        PHONE_EXT(255)     TYPE C,
        PHONE_CNTRYCODE    TYPE CHAR255,
        FAX_NUMBER(255)    TYPE C,
        FAX_CNTRYCODE(255) TYPE C,
        MOBILE_NUMBER(255) TYPE C,
        FUNC_NAME(255)     TYPE C,
        MOBILE_CNTRYCODE   TYPE CHAR255,
        ADMIN(255)         TYPE C,
        CNTCT_ID(255)      TYPE C,
      END OF GS_CNTCTS.

TYPES:BEGIN OF GS_REMITTANCE,
        REF_ID(255)        TYPE C,
        ADDRESS1           TYPE CHAR255,
        ADDRESS2           TYPE CHAR255,
        ADDRESS3           TYPE CHAR255,
        CITY               TYPE CHAR255,
        CNTRY              TYPE CHAR255,
        STATE              TYPE CHAR255,
        ZIP                TYPE CHAR255,
        PAYEE_NAME         TYPE CHAR255,
        LOCATION           TYPE CHAR255,
        ALT_PAYEE_FLG(255) TYPE C,
        COUNTY             TYPE CHAR255,
      END OF GS_REMITTANCE.

TYPES:BEGIN OF GS_PAYMENTDATA,
        REF_ID(255)        TYPE C,
        TYPE(255)          TYPE C,
        EMAIL_ADDRESS(255) TYPE C,
        ACCOUNT_TYPE(255)  TYPE C,
        BANK_ROUTING_NO    TYPE CHAR255,
        BANK_NAME(255)     TYPE C,
        BANK_ACCOUNT_NO    TYPE CHAR255,
        COMMENT(255)       TYPE C,
        ACH_DEC(255)       TYPE C,
        ACHCCDPLUS(255)    TYPE C,
        ACHCTX(255)        TYPE C,
        OTHER_DESC(255)    TYPE C,
        COUNTY(255)        TYPE C,
      END OF GS_PAYMENTDATA.

TYPES:BEGIN OF GS_BANKDETAIL,
        REF_ID(50)      TYPE C,
        ACCNAME(50)     TYPE C,
        NAME(50)        TYPE C,
        ACC_NUMBER(50)  TYPE C,
        ADDRESS         TYPE CHAR255,
        SWIFT_CODE(50)  TYPE C, "20
        ROUT_NUMBER(50) TYPE C, "20
        IBAN(50)        TYPE C, "25
        CURRENCY(50)    TYPE C, "3
      END OF GS_BANKDETAIL.

TYPES:BEGIN OF GS_INT_BANKDETAIL,
        REF_ID(50)      TYPE C,
        ACCNAME(50)     TYPE C,
        NAME(50)        TYPE C,
        ACC_NUMBER(50)  TYPE C,
        ADDRESS         TYPE CHAR255,
        SWIFT_CODE(50)  TYPE C, "20
        ROUT_NUMBER(50) TYPE C, "20
        IBAN(50)        TYPE C, "25
        CURRENCY(50)    TYPE C, "3
      END OF GS_INT_BANKDETAIL.

TYPES:BEGIN OF GS_TAXDETAIL,
        REF_ID(50)  TYPE C,
        TAXID(30)   TYPE C,
        GST(50)     TYPE C,
        VC_1099(50) TYPE C,
      END OF GS_TAXDETAIL.

TYPES:BEGIN OF GS_ACK1,
        REF_NO(255) TYPE C,
      END OF GS_ACK1.


********FOR EXPENSE DATA

TYPES:BEGIN OF GS_EXPDATA,
        REF_ID(255)        TYPE C,
        WORKFLOW_TYPE(255) TYPE C,
      END OF GS_EXPDATA,

      BEGIN OF GS_HDATA,
        REF_ID(255)              TYPE C,
        SSP_INVOICE_NO(255)      TYPE C,
        TITLE(255)               TYPE C,
        INV_NO(255)              TYPE C,
        EMPLOYEE_ID(255)         TYPE C,
        EMPLOYEE_FIRST_NAME(255) TYPE C,
        EMPLOYEE_LASR_NAME(255)  TYPE C,
        CREATED_DATE(255)        TYPE C,
        CREATED_TIME(255)        TYPE C,
        EXPENSE_DATE(255)        TYPE C,
        CURRENCY(255)            TYPE C,
        SUB_TOTAL(255)           TYPE C,
        STATUS(255)              TYPE C,
        NOTES(255)               TYPE C,
        CREATOR(255)             TYPE C,
        REQUESTOR_EMAIL(255)     TYPE C,
        REQUESTER(255)           TYPE C,
      END OF GS_HDATA,

      BEGIN OF GS_LDATA,
        REF_ID(255)       TYPE C,
        NAME(255)         TYPE C,
        EXPENSE_TYPE(255) TYPE C,
        DATE(255)         TYPE C,
        THROUGHDATE(255)  TYPE C,
        COST_CENTER(255)  TYPE C,
        GL_ACC_NO(255)    TYPE C,
        AMOUNT(255)       TYPE C,
        DEPART_DATE(255)  TYPE C,
        DEPART_TIME(255)  TYPE C,
        RETURN_DATE(255)  TYPE C,
        RETURN_TIME(255)  TYPE C,
        COMMENTS(255)     TYPE C,
      END OF GS_LDATA,

      BEGIN OF GS_LATTCH,
        REF_ID(255)          TYPE C,
        AR_ID(255)           TYPE C,
        AR_DOCID(255)        TYPE C,
        FL_NAME(255)         TYPE C,
        FL_TYPE(255)         TYPE C,
        ATTID(255)           TYPE C,
        DOC_EXPIRY_DATE(255) TYPE C,
        DOC_EXPIRY_TIME(255) TYPE C,
        CREATED_DATE(255)    TYPE C,
        CREATED_TIME(255)    TYPE C,
        CREATOR(255)         TYPE C,
      END OF GS_LATTCH,

      BEGIN OF GS_ATTCHMNTS,
        REF_ID(255)          TYPE C,
        AR_ID(255)           TYPE C,
        AR_DOCID(255)        TYPE C,
        FL_NAME(255)         TYPE C,
        FL_TYPE(255)         TYPE C,
        ATTID(255)           TYPE C,
        DOC_EXPIRY_DATE(255) TYPE C,
        DOC_EXPIRY_TIME(255) TYPE C,
        CREATED_DATE(255)    TYPE C,
        CREATED_TIME(255)    TYPE C,
        CREATOR(255)         TYPE C,
      END OF GS_ATTCHMNTS,

      BEGIN OF GS_LOGS,
        REF_ID(255)        TYPE C,
        STEP(255)          TYPE C,
        SEQ(255)           TYPE C,
        ACTIVITY(255)      TYPE C,
        USER_ID(255)       TYPE C,
        ACTUAL_USER(255)   TYPE C,
        ACTIVITY_TEST(255) TYPE C,
        LOG_DATE(255)      TYPE C,
        LOG_TIME(255)      TYPE C,
        CHANNEL(255)       TYPE C,
      END OF GS_LOGS,

      BEGIN OF GS_COMMENTS,
        REF_ID(255)       TYPE C,
        STEP(255)         TYPE C,
        SEQ(255)          TYPE C,
        COMMENT_TEXT(255) TYPE C,
        LOG_DATE(255)     TYPE C,
        LOG_TIME(255)     TYPE C,
      END OF GS_COMMENTS,

*      BEGIN OF GS_STGWFLOW,
*        REF_ID(255)       TYPE C,
*        CANEDIT(255)      TYPE C,
*        STL(255)          TYPE C,
*        WORK_ITEM_ID(255) TYPE C,
*        STAGE_NUMBER(255) TYPE C,
*        STAGE_TYPE(255)   TYPE C,
*        STAGE_NAME(255)   TYPE C,
*        AGENT(255)        TYPE C,
*      END OF GS_STGWFLOW,
*
*      BEGIN OF GS_STGUSRS,
*        APPROVER(255) TYPE C,
*        REF_ID(255)   TYPE C,
*      END OF GS_STGUSRS,
*
*      BEGIN OF GS_STGACTYS,
*        REF_ID(255)      TYPE C,
*        NAME(255)        TYPE C,
*        CODE(255)        TYPE C,
*        LABLE(255)       TYPE C,
*        COMMENT_REQ(255) TYPE C,
*        ENABLED(255)     TYPE C,
*      END OF GS_STGACTYS,
      BEGIN OF GS_RESULTS,
        STATUS(255)  TYPE C,
        MESSAGE(255) TYPE C,
      END OF GS_RESULTS.

DATA : IT_EXPDATA  TYPE STANDARD TABLE OF GS_EXPDATA INITIAL SIZE 1,
       IT_HDATA    TYPE STANDARD TABLE OF GS_HDATA INITIAL SIZE 1,
       IT_LDATA    TYPE STANDARD TABLE OF GS_LDATA INITIAL SIZE 1,
       IT_LATTCH   TYPE STANDARD TABLE OF GS_LATTCH INITIAL SIZE 1,
       IT_ATTCH    TYPE STANDARD TABLE OF GS_ATTCHMNTS INITIAL SIZE 1,
       IT_LOG1     TYPE STANDARD TABLE OF GS_LOGS INITIAL SIZE 1,
       IT_COMMENTS TYPE STANDARD TABLE OF GS_COMMENTS INITIAL SIZE 1,
*       IT_STGWFLOW TYPE STANDARD TABLE OF GS_STGWFLOW INITIAL SIZE 1,
       IT_RESULT   TYPE STANDARD TABLE OF GS_RESULTS INITIAL SIZE 1,
       GT_STATUS   TYPE TABLE OF TY_STATUS,
       WA_STATUS   TYPE TY_STATUS,
       WA_RESULT   TYPE GS_RESULTS,
*       WA_STGWFLOW TYPE GS_STGWFLOW,
       WA_COMMENT  TYPE GS_COMMENTS,
       WA_LOG1     TYPE GS_LOGS,
       WA_ATTCH    TYPE GS_ATTCHMNTS,
       WA_LATTCH   TYPE GS_LATTCH,
       WA_LDATA    TYPE GS_LDATA,
       WA_HDATA    TYPE GS_HDATA,
       WA_EXPDATA  TYPE GS_EXPDATA.


DATA:IT_ATTACH_EXP  TYPE TABLE OF /SDOCS/SSPY_ATTA,
     IT_LOG_EXP     TYPE TABLE OF /SDOCS/SSPY_LOG,
     WA_LOG_EXP     TYPE /SDOCS/SSPY_LOG,
     WA_HD_EXP      TYPE /SDOCS/SSPY_HD,
     WA_LN_EXP      TYPE /SDOCS/SSPY_LN,
     IT_LN_EXP      TYPE STANDARD TABLE OF /SDOCS/SSPY_LN INITIAL SIZE 1,
     WA_ATTACH_EXP  TYPE /SDOCS/SSPY_ATTA,
     IT_LATTACH_EXP TYPE TABLE OF /SDOCS/S1_ATTAL,
     WA_LATTACH_EXP TYPE /SDOCS/S1_ATTAL.
DATA LV_LINE2 TYPE NUMC5.

TYPES: BEGIN OF TY_VMA,
         REF_ID(255)                 TYPE C,
         COMPANY_CODE(255)           TYPE C,
         PAYMENT_METHOD(255)         TYPE C,
         PAYMENT_TERMS(255)          TYPE C,
         RELEASE_GROUP(255)          TYPE C,
         RECONCILIATION_ACCOUNT(255) TYPE C,
         PURCHASING_GROUP(255)       TYPE C,
         PURCHASING_ORG(255)         TYPE C,
       END OF  TY_VMA.
TYPES:BEGIN OF TY_DBE,
        REF_ID(50)          TYPE C,
        DBE(255)            TYPE C,
        DOC_TYPE(255)       TYPE C,
        EXPIRATION_DATE(50) TYPE C,
      END OF TY_DBE.

TYPES:BEGIN OF TY_PC,
        REF_ID(50)            TYPE C,
        PRODUCT_CATAGORY(255) TYPE C,
        CATEGORY_CODE(255)    TYPE C,
        CATEGORY_NAME(255)    TYPE C,
      END OF TY_PC.
DATA:       LV_POMORE_LINES,
PO_LINES    TYPE SY-TABIX.
DATA: LV_FAILED .

DATA:L_V   TYPE STRING.
DATA:L_V1  TYPE STRING.
DATA:CNT_I TYPE INT4.

DATA:LV_CHECK_DOCID TYPE /SDOCS/SSPY_DOCID.
DATA:LT_RACT TYPE TABLE OF /SDOCS/SSPY_RACT,
     WA_RACT TYPE /SDOCS/SSPY_RACT.
DATA:WA_DDOCID TYPE /SDOCS/S1_DDOCID,
     GT_DDOCID TYPE TABLE OF /SDOCS/S1_DDOCID.
DATA:LT_EXCP TYPE TABLE OF /SDOCS/SSPY_REXP,
     LS_EXCP TYPE /SDOCS/SSPY_REXP,
     GT_SBUS TYPE  TABLE OF /SDOCS/S1_RWF_ST,
     WA_SBUS TYPE /SDOCS/S1_RWF_ST.

DATA:LT_RWFUSR TYPE TABLE OF /SDOCS/S1_RWFUSR,
     LS_RWFUSR TYPE /SDOCS/S1_RWFUSR.
DATA:LT_ADR6 TYPE TABLE OF TT_AR6,
     LS_ADR6 TYPE TT_AR6.
DATA:LT_USR21 TYPE TABLE OF TT_USR21,
     LS_USR21 TYPE TT_USR21.

DATA:GT_BANKDETAIL     TYPE TABLE OF GS_BANKDETAIL,
     GT_INT_BANKDETAIL TYPE TABLE OF GS_INT_BANKDETAIL,
     WA_BANKDETAIL     TYPE GS_BANKDETAIL,
     WA_INT_BANKDETAIL TYPE GS_INT_BANKDETAIL.

DATA:GT_TAXDETAIL TYPE TABLE OF GS_TAXDETAIL,
     WA_TAXDETAIL TYPE GS_TAXDETAIL.

DATA:WA_BNDT  TYPE /SDOCS/S1_VNDR_B,
     LT_BNDT  TYPE TABLE OF  /SDOCS/S1_VNDR_B,
     LV_TABIX TYPE NUMC5.

*data:gv_docid type /sdocs/s1_vndr_h-docid.
DATA: GT_T_ATTACH      TYPE TABLE OF /SDOCS/SSPY_ATTA,
      GT_VNDR_MVI      TYPE TABLE OF /SDOCS/S1_VNDR_M,
      GT_VNDR_PRDCTG   TYPE TABLE OF /SDOCS/S1_VNDR_P,
      GT_CNTCTS        TYPE TABLE OF /SDOCS/S1_VNDR_C,
      GT_T_ACK         TYPE TABLE OF GS_ACK1,
      GT_T_ADDRESS     TYPE TABLE OF GS_ADDRESS,
      GT_T_SDATA       TYPE TABLE OF GS_SDATA_VRR,
      GT_T_BNK_DTLS    TYPE TABLE OF GS_BNK_DTLS,
      GT_T_ATT         TYPE TABLE OF GS_ATT,
      GT_T_CNTCTS      TYPE TABLE OF GS_CNTCTS,
      GT_PAYMENTDATA   TYPE TABLE OF GS_PAYMENTDATA,
      GT_T_REMITTANCE  TYPE TABLE OF GS_REMITTANCE,
      GT_T_SUP_DATA    TYPE TABLE OF /SDOCS/S1_VNDR_H,
      GT_T_VNDR_CNTCTS TYPE TABLE OF /SDOCS/S1_VNDR_C,
      GT_LOG11         TYPE TABLE OF GS_LOG,
      GT_VMA           TYPE TABLE OF TY_VMA,
      GT_DBE           TYPE TABLE OF TY_DBE,
      GT_PC            TYPE TABLE OF TY_PC.

DATA:L_AGT_USERS  TYPE /SDOCS/S1_AGTUSR,
     LT_AGT_USERS TYPE TABLE OF /SDOCS/S1_AGTUSR.


DATA:GV_AGENT  TYPE /SDOCS/SSPY_SGC-CONFIG_VALUE.
DATA:LV_BUKRS TYPE BUKRS.
DATA:LV_ATTACH TYPE /SDOCS/SSPY_DOCID.

DATA: "wa_attach      type /sdocs/sspy_atta,
  WA_SUP_DATA    TYPE /SDOCS/S1_VNDR_H,
  WA_CNTCTS_T    TYPE /SDOCS/S1_VNDR_C,
  WA_SDATA       TYPE GS_SDATA_VRR,
  WA_L_BNK_DTLS  TYPE GS_BNK_DTLS,
*      wa_att         type gs_att,
  WA_CNTCTS      TYPE GS_CNTCTS,
  WA_REMITTANCE  TYPE GS_REMITTANCE,
  WA_VNDR_HDATA1 TYPE /SDOCS/S1_VNDR_H,
  WA_PAYMENTDATA TYPE GS_PAYMENTDATA,
  WA_VMA         TYPE TY_VMA,
*      wa_mvi         type gs_mvi,
*      wa_pca         type gs_pca,
  WA_ACK         TYPE GS_ACK1,
  WA_ADDRESS     TYPE GS_ADDRESS.
DATA:"lv_config  type /sdocs/sspy_sgc-config_value,
  LV_CONFIG1 TYPE /SDOCS/SSPY_SGC-CONFIG_VALUE,
  LV_CONFIG2 TYPE /SDOCS/SSPY_SGC-CONFIG_VALUE.
DATA:P_PROFLE TYPE /SDOCS/SSPY_SPRF-PROFILE_ID.
DATA:GV_DESC      TYPE CHAR255,
     GV_SYM_K     TYPE SY-TABIX,
     GV_CH        TYPE C,
     GV_CH1       TYPE STRING,
     GV_STR       TYPE STRING,
     GV_SYM_STR   TYPE STRING,
     GV_SYM_S_STR TYPE STRING,
     GV_INT1      TYPE STRING,
     GV_BUFFER    TYPE XSTRING,
     GV_BUFFER1   TYPE STRING,
     GV_STR_LEN   TYPE SY-TABIX,
     GV_INT       TYPE I,
     P_AC_EXT     TYPE /SDOCS/SSPY_HTTP_EXT,
     CONV         TYPE REF TO CL_ABAP_CONV_OUT_CE.
