PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/SDOCS/SSPY_SPRF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /SDOCS/SSPY_SPRF-PROFILE_ID .
    FIELD /SDOCS/SSPY_SPRF-PROFILE_DES .
    FIELD /SDOCS/SSPY_SPRF-SAP_SID .
    FIELD /SDOCS/SSPY_SPRF-APP_ID .
    FIELD /SDOCS/SSPY_SPRF-APP_SECRET_ID .
    FIELD /SDOCS/SSPY_SPRF-ENCODE_METHOD .
    FIELD /SDOCS/SSPY_SPRF-RFC_DEST .
    FIELD /SDOCS/SSPY_SPRF-SERVER_ID .
    FIELD /SDOCS/SSPY_SPRF-SERVER_PORT .
    FIELD /SDOCS/SSPY_SPRF-FTP_SERVER .
    FIELD /SDOCS/SSPY_SPRF-FTP_UID .
    FIELD /SDOCS/SSPY_SPRF-FTP_PWD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /SDOCS/SSPY_SPRF-PROFILE_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
