PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /SDOCS/SSPY_SPRF-PROFILE_ID .
    FIELD /SDOCS/SSPY_SPRF-PROFILE_DES .
    FIELD /SDOCS/SSPY_SPRF-SAP_SID .
    FIELD /SDOCS/SSPY_SPRF-APP_ID .
    FIELD /SDOCS/SSPY_SPRF-APP_SECRET_ID .
    FIELD /SDOCS/SSPY_SPRF-ENCODE_METHOD .
    FIELD /SDOCS/SSPY_SPRF-RFC_DEST .
    FIELD /SDOCS/SSPY_SPRF-SERVER_ID .
    FIELD /SDOCS/SSPY_SPRF-SERVER_PORT .
    FIELD /SDOCS/SSPY_SPRF-FTP_SERVER .
    FIELD /SDOCS/SSPY_SPRF-FTP_UID .
    FIELD /SDOCS/SSPY_SPRF-FTP_PWD .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
*{   INSERT         S4HK903108                                        1
chain.
*}   INSERT
*{   INSERT         S4HK903108                                        1
  FIELD /SDOCS/SSPY_SPRF-APP_SECRET_ID.
  MODULE SET_SECURITY_UPDATE on CHAIN-REQUEST.
endchain.
*}   INSERT
 chain.
    FIELD /SDOCS/SSPY_SPRF-PROFILE_ID .
  module detail_pai.
 endchain.
